server:
  port: 8090
spring:
  application:
    name: short-url
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.short-url/short-db
    username: admin
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2
      settings:
        trace: false
        web-allow-others: false
